name: abacus
description: A simple, but feature-rich, counter for tabletop games.

publish_to: 'none'
version: 1.1.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  wakelock: ^0.6.2
  url_launcher: ^6.1.9
  loop_page_view: ^1.2.1
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Mana
      fonts:
        - asset: fonts/mana.ttf
